# Generated by Django 2.2 on 2022-02-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='name',
        ),
    ]
