# Generated by Django 2.2 on 2022-02-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_work_worktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='location',
        ),
    ]
