# Generated by Django 2.2 on 2022-02-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220220_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
