# Generated by Django 2.2 on 2022-04-02 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_worktype_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Applications'),
        ),
    ]
